<?phprequire 'koneksi.php';koneksi_buka();$id_reqinventory = $_POST['id'];$data = mysql_fetch_array(mysql_query("SELECT * FROM vw_request_inventory WHERE id_reqinventory =".$id_reqinventory.""));if($id_reqinventory > 0) { 	$title = $data['title'];	$user_name = $data['user_name'];	$user_nik =  $data['user_nik'];	$starttime_available =  $data['starttime_available'];	$endtime_available =  $data['endtime_available'];	$items_name =  $data['items_name'];	$request_by =  $data['request_by'];	$approval_name =  $data['approval_name'];	$kebutuhan_descr =  $data['kebutuhan_descr'];} else {	$title = '';	$user_name = '';	$user_nik = '';	$starttime_available = '';	$endtime_available = '';	$items_name = '';	$request_by = '';	$approval_name = '';	$kebutuhan_descr = '';}?>
<script type="text/javascript" src="scripts/jquery.min.js"></script>
<script type="text/javascript" src="scripts/jquery.form.js"></script>
<style>body{	font-family:arial;}
.preview
{	width:200px;
	border:solid 1px #dedede;
	padding:10px;}#preview{
	color:#cc0000;
	font-size:12px
}</style>
<script type="text/javascript" src="./js/flowplayer-3.2.6.min.js"></script>	<script type="text/javascript" src="./js/jquery.js"></script>
<form class="form-horizontal" id="form-videoetail">	<div class="control-group">		<label class="control-label" for="title">Title Subject</label>		<div class="controls">			<input type="text" id="title" class="input-medium" name="title" value="<?php echo $title ?>" placeholder="isikan Nama title subject" title="We ask for your meeting title." readonly>		</div>	</div>	<div class="control-group">		<label class="control-label" for="user_name">Request By Name</label>		<div class="controls">			<!--<input type="text" id="user_name" class="input-medium" name="user_name" value="<!?php echo $user_name ?>" placeholder="isikan Nama Peminjam">-->			<input type="text" id="user_name" class="input-medium" name="user_name" value="<?php echo $_SESSION[user_realname] ?>" placeholder="isikan Nama Peminjam" readonly>		</div>	</div>	<div class="control-group">		<label class="control-label" for="user_telpon">Request By Phone</label>		<div class="controls">			<!--<input type="text" id="user_telpon" class="input-medium" name="user_telpon" value="<!?php echo $user_telpon ?>" placeholder="isikan telpon Peminjam">-->			<input type="text" id="user_telpon" class="input-medium" name="user_telpon" value="<?php echo $_SESSION[telpon] ?>" placeholder="isikan telpon Peminjam" readonly>		</div>	</div>			<div class="control-group">		<label class="control-label" for="starttime_available">Tgl Start Room Reserve</label>		<div class="controls">			<input type="text" id="starttime_available" class="input-medium" name="starttime_available" value="<?php echo $starttime_available ?>" readonly>		</div>	</div>				<div class="control-group">		<label class="control-label" for="endtime_available">Tgl Finish Room Reserve</label>		<div class="controls">			<input type="text" id="endtime_available" class="input-medium" name="endtime_available" value="<?php echo $endtime_available ?>" readonly>		</div>	</div>			<div class="control-group">			<label class="control-label" for="items_name">Meeting Rooms Available</label>			<div class="controls">				<input type="text" id="items_name" class="input-medium" name="items_name" value="<?php echo $items_name ?>" readonly>			</div>	</div>		</form>
<?php	koneksi_tutup();?>

